apiVersion: v1
kind: Service
metadata:
  name: kubernetes-intro
  labels:
    app: kubernetes-intro
spec:
  ports:
    - port: 5000
  selector:
    app: kubernetes-intro
    tier: frontend
  type: NodePort
